spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    username: bountyhunter
#    password: tMYETHedGeiiZrMr
#    username: root
#
    username: root
    password: kira
    url: jdbc:mysql://127.0.0.1/bountyhunter?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.163.com
    username: fate1342746626@163.com
    password: a456789
#        port: 465
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
         smtp:
           auth: true
           socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465

#              starttls:
#                enable: true
#                required: true

  thymeleaf:
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
      cache: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/#,file:${img.location}

server:
#    context-path: /bountyhunter
    port: 8080

#  图片上传保存路径
img:
  location: /www/wwwroot/aeaeae.top
#  mail:
#      host: smtp.163.com
#      username: fate1342746626@163.com
#      password: a456789
##      port: 25
#      default-encoding: UTF-8
#      protocol: smtp
#      properties:
#        mail:
#          smth:
#            auth: true
#            starttls:
#              enable: true
#              required: true